
'use client'
import './globals.css'
import { Genos } from 'next/font/google'
import profilePic from '../public/images/profilebw.jpg'
import Image from 'next/image'
import headerStyle from './header.module.css'
import { useState} from "react";


 
const genos = Genos({
  subsets: ['latin']

})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}






export default function RootLayout({ children }) {
  const [data, setData] = useState({name: '', email: '', message: ''});
  
const onSubmitForm = async () => {

  console.log(data)
  const response = await fetch('http://localhost:5000/api/express/contact', {
    method: 'POST',
    body: JSON.stringify(data)
  })

  // Handle response if necessary
  const returndata = await response.json()
  console.log(returndata)
  // ...
}


  
  return (
    <html lang="en" className={genos.className}>
      <body>
        <header className={headerStyle.headercss}>
            <aside className="profile">
                <Image
               
                src={profilePic}
                alt='Picture of Andrew Watts (awattsdev)'
                />
                
                <div className="mask">
                    
                </div>
               
            </aside>
            <h1>Andrew Watts Development</h1>
          </header> 
         
      {children}
        <footer>

        <section>
     
        <form
        onSubmit={(e) => {
          e.preventDefault();
          onSubmitForm();
        }}
      >

             <h2>Contact me here!</h2>
                
            <label >Name</label>
            <br/>
            <input  type="text" name="name"  required="" onChange={(e) => setData( prevData => ({ ...prevData, name: e.target.value }))} />
            <br/>
            <label >Email address</label>
            <br/>
            <input  type="text" name="email" onChange={(e) => setData(prevData => ({ ...prevData, email: e.target.value }))}  required=""/>
            <br/>
            <label>Message</label>
            <br/>
            <textarea  name="message" rows="6"  cols="25" onChange={(e) => setData( prevData => ({ ...prevData, message: e.target.value }))}></textarea>


               


        <button type="submit">Submit</button>
      </form>
        </section>


        <section >
                <h2>Links</h2>
                <h2>I'm also active on the following platforms</h2>
                <aside>
                    
                </aside>
            </section>
        </footer>

      </body>
    </html>
  )
}
