import './globals.css'
import { Genos } from 'next/font/google'
import profilePic from '../public/images/profilebw.jpg'
import Image from 'next/image'
import headerStyle from './header.module.css'
import ContactForm from '@/components/contact_form'

 
const genos = Genos({
  subsets: ['latin']

})




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={genos.className}>
      <body>
        <header className={headerStyle.headercss}>
            <aside className="profile">
                <Image
               
                src={profilePic}
                alt='Picture of Andrew Watts (awattsdev)'
                />
                
                <div className="mask">
                    
                </div>
               
            </aside>
            <h1>Andrew Watts Development</h1>
          </header> 
         
      {children}
        <footer>

        <section>
          <ContactForm />
        </section>


        <section class="social-media">
                <h2>Links</h2>
                <h2>I'm also active on the following platforms</h2>
                <aside>
                    
                </aside>
            </section>
        </footer>

      </body>
    </html>
  )
}
